#!/bin/bash

if [ $# = 0 ]
then
    java -classpath server Core
else
    if [[ $* =~ "build" ]]
    then
        javac server/*.java
    fi
    if [[ $* =~ "--verbose" ]]
    then
        java -classpath server Core --verbose
    elif [[ $* =~ "--debug" ]]
    then
        java -classpath server Core --verbose
    else
        java -classpath server Core
    fi
fi
